ARG VPP_AGENT
FROM ${VPP_AGENT} as runtime
RUN rm /opt/vpp-agent/dev/etcd.conf /opt/vpp-agent/dev/kafka.conf; echo 'Endpoint: "0.0.0.0:9112"' > /opt/vpp-agent/dev/grpc.conf; echo "disabled: true" > /opt/vpp-agent/dev/linux-plugin.conf
COPY dataplane/vppagent/conf/vpp/startup.conf /etc/vpp/vpp.conf
COPY examples/conf/vppagent-firewall-nse/supervisord.conf /etc/supervisord/supervisord.conf
